`salmon-fetch` with updated checks and test cases
DeFiCh/oracle-adapters pull request #43
Opened 2021-10-13 16:22 UTC by joeldavidw

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #11 & #31 

#### Additional comments?:

2021-10-13 16:33 UTC, fuxingloh requested changes

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/src/Fetch.ts
> +import BigNumber from 'bignumber.js'
`Fetch.ts` is redundant since we have `fetchAsJson.ts`, you should move this into AssetPrice since the concern is together.

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/src/Fetch.ts
> +import BigNumber from 'bignumber.js'
don't need to export the function within isPriceValid either within `AssetPrice.ts`.

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> + * @param {BigNumber} timestamp (seconds) in BigNumber, if number it will automatically be converted.
```suggestion
 * @param {number | BigNumber} timestamp (seconds) in BigNumber, if number it will automatically be converted.
```

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
>   * Helper utility to create new AssetPrice.
```suggestion
 * Helper utility to create new AssetPrice with automatic conversion of types to required types.
```

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/__test__/AssetPrice.spec.ts
> +    const prices = await coingecko(['BTC', 'ETH', 'DOGE'])
you should use fetchAsJson to test this, not via coingecko.

2021-10-13 16:33 UTC, fuxingloh commented on packages/salmon-fetch/__test__/AssetPrice.spec.ts
> +    const prices = await coingecko(['BTC', 'ETH', 'DOGE'])
Testing the usage of `fetchAsJson`, not the adapters themselves. Hence your req/res can arbitrary as long as it can conform to the fetch method.

2021-10-13 17:56 UTC, monstrobishi commented
Shouldn't the IsValid checks live inside `salmon-filter`?

2021-10-13 18:04 UTC, monstrobishi commented
@fuxingloh on another note related to the above question, I noticed that AbstractFilter throws on error, or at least the reference implementation of NPF does:
https://github.com/DeFiCh/oracle-adapters/blob/main/packages/salmon-filter/src/filters/NonPositiveFilter.ts#L12

This could cause an issue where a few prices are valid and one is not, I'm assuming if we throw here it would stall the pipeline, ideally we would want to filter out the bad ones and just submit the ones that are valid.

2021-10-13 18:32 UTC, fuxingloh commented
> @fuxingloh on another note related to the above question, I noticed that AbstractFilter throws on error, or at least the reference implementation of NPF does: https://github.com/DeFiCh/oracle-adapters/blob/main/packages/salmon-filter/src/filters/NonPositiveFilter.ts#L12
> 
> This could cause an issue where a few prices are valid and one is not, I'm assuming if we throw here it would stall the pipeline, ideally we would want to filter out the bad ones and just submit the ones that are valid.

https://github.com/DeFiCh/oracle-adapters/blob/7f9178517a6549904164942aa166686a732c9ddb/packages/salmon-filter/src/AbstractFilter.ts#L38-L41

For some situations, we can warn. 

But for `NonPositiveFilter`, the design idea is price can never be negative, there must be something fundamentally wrong with the `adapter` hence throw an error and exit. 

> Edited Additionally: 

Since the `salmon-filter` run an entire oracle adapter and filter them together, if that adapter produces one false result we can safely assume all is bad.

https://github.com/DeFiCh/oracle-adapters/blob/7f9178517a6549904164942aa166686a732c9ddb/packages/salmon-filter/src/AbstractFilter.ts#L46-L50

2021-10-13 18:35 UTC, fuxingloh commented
> Shouldn't the IsValid checks live inside `salmon-filter`?

Basic checks are required for type conformation, such that it conforms to the `interface AssetPrice`. As `JSON.parse()` returns `any` and you cannot assume the `type` is correct. This is to make it easy for `salmon-filter` implementation where the interface types can be trusted without reverifying,

2021-10-13 18:45 UTC, monstrobishi commented
@fuxingloh ok understood. I guess the situations where we can just warn and filter include timestamp check (filtering out old prices) and legimate but erratic price movements (filtering out volatile movement specific to one asset).

2021-10-13 18:46 UTC, fuxingloh requested changes

2021-10-13 18:46 UTC, fuxingloh commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
There might be a provided timestamp for that oracle, possible to get a timestamp from the oracle itself and use that instead?

2021-10-13 18:46 UTC, fuxingloh commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
Anyway `Date.now()` is ms, this is seconds.

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +  return false
should rearrange to return early

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +  return false
should rearrange to return early, for better reliability, return early and keep the positive condition below. 

When you read conditions such as these, it makes it easier to grasp when in your mind linearly, you read the conditions and checks out the falses until you reach the true. A linear checklist of sorts without any if staircasing.

Linear Checklist:
1. is not big number, return false
2. is nan, return false
3. is not finite, return false
4. finally true

Complex Checklist:
1. Is bignumber, is not nan, is finite, return true
2. return false
3

@monstrobishi I left a review on whale side similar to this about return early pattern

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +function isTimestampValid (timestamp: number | BigNumber): boolean {
Should briefly describe what you are rejecting

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +    timestamp: BigNumber.isBigNumber(timestamp) ? timestamp : new BigNumber(timestamp)
should check all type conform to what is required, token = string, currency = string

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> + * Helper utility to create new AssetPrice with automatic conversion of types to required types.
```suggestion
 * Helper utility to create new AssetPrice with automatic validation and conversion of types to required types.
```

2021-10-13 18:46 UTC, fuxingloh commented on packages/salmon-fetch/__test__/FetchAsJson.spec.ts
> +            doge: 123
should add a string currency and check it's string also just in case

2021-10-13 18:46 UTC, fuxingloh commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
Are we using seconds or ms? Should document

2021-10-13 18:49 UTC, monstrobishi commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
@fuxingloh I left a note on the ticket for this within salmon prefer to standardise to ms for general js compatibility and precision, when publishing we divide by 1000

2021-10-13 18:54 UTC, monstrobishi commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
Coingecko is unfortunately one of the very few providers that don't supply us with a timestamp

2021-10-13 18:55 UTC, monstrobishi commented on adapters/src/coingecko.ts
> +    return newAssetPrice(internal, res.data[external].usd, 'USD', Date.now())
Sorry comment was on this ticket

https://github.com/DeFiCh/oracle-adapters/issues/31

2021-10-13 18:58 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +  return false
I guess it's highly subjective, just my thoughts.

2021-10-13 19:02 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> +  return false
Another example for reference:

![image](https://user-images.githubusercontent.com/4266087/137196571-91f3e637-3d59-4fb6-8bbe-a64735fcaebe.png)

vs 

![image](https://user-images.githubusercontent.com/4266087/137196707-c97a8b3c-8ca3-4e64-ac32-4f1bd6aca404.png)

2021-10-14 05:12 UTC, fuxingloh requested changes

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/__test__/FetchAsJson.spec.ts
> +describe('single asset price fetch', () => {
```suggestion
```

don't need this describe block, I think it's redundant in this context

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/__test__/FetchAsJson.spec.ts
> +  describe('FetchAsJson', () => {
```suggestion
  describe('FetchAsJson', () => {
    afterEach(() => {
    jest.clearAllMocks()
    nock.cleanAll()
  })
```

afterEach should be nested inside FetchAsJson

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/src/AssetPrice.ts
> + * @param {number | BigNumber} timestamp (seconds) in BigNumber, if number it will automatically be converted. If datetime is in string, Date.parse(datetime).toNumber() could be used.
```suggestion
 * @param {number | BigNumber} timestamp (milliseconds since epoch) in BigNumber, if number it will automatically be converted. If datetime is in string, Date.parse(datetime).toNumber() could be used.
```

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/__test__/AssetPrice.spec.ts
> +describe('PriceAsset interface', () => {
```suggestion
```

I won't include this because it's not very accurate. You are rather testing everything inside AssetPrice at this point so I think you can just leave it describe block out of this one.

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/__test__/AssetPrice.spec.ts
> +describe('PriceAsset interface', () => {
instead, it should be 4 blocks:

1. describe('AssetPrice.amount')
2. describe('AssetPrice.currency') 
3. describe('AssetPrice.token') 
4. describe('AssetPrice.timestamp')

2021-10-14 05:12 UTC, fuxingloh commented on packages/salmon-fetch/__test__/AssetPrice.spec.ts
> +  })
```ts
  it('should exclude invalid timestamp - string', () => {
    expect(() => {
      newAssetPrice('APPL', '1', 'USD', 'string' as any)
    }).toThrowError(Error('timestamp is not number or BigNumber'))
  })
```

should also test other types

2021-10-14 11:01 UTC, fuxingloh approved these changes

2021-10-15 04:27 UTC, monstrobishi approved these changes

2021-10-15 04:28 UTC, merged