Added CurrencyFilter
DeFiCh/oracle-adapters pull request #61
Opened 2021-10-19 17:30 UTC by joeldavidw

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Added CurrencyFilter with tests

#### Which issue(s) does this PR fixes?:

Fixes #51

2021-10-20 09:50 UTC, fuxingloh requested changes

2021-10-20 09:50 UTC, fuxingloh commented on packages/salmon-filter/src/filters/CurrencyFilter.ts
> +
```suggestion
```

I believe this is redundant since you only allow 'USD' regardless

2021-10-20 09:52 UTC, fuxingloh commented
Conflict need to rebase

2021-10-21 04:28 UTC, fuxingloh approved these changes

2021-10-21 04:34 UTC, monstrobishi approved these changes

2021-10-21 04:35 UTC, merged