migrate finnhubb-forex
DeFiCh/oracle-adapters pull request #71
Opened 2021-10-21 08:49 UTC by canonbrother

#### What kind of PR is this?:

/kind chore
/kind refactor

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Fixes #36 (part of #32)

#### Additional comments?:

2021-10-22 08:05 UTC, monstrobishi commented on adapters/__tests__/finnhubb-forex.test.ts
> +    expect(prices[0].token).toStrictEqual('XAU')
Let's validate the whole structure jellyfish style see: https://github.com/DeFiCh/oracle-adapters/pull/75/files#r734318580

2021-10-26 06:02 UTC, joeldavidw requested changes

2021-10-26 06:02 UTC, joeldavidw commented on adapters/src/finnhubb-forex.ts
> +  const response = await fetch(fetchPath, {
Let's use [fetchAsJson](https://github.com/DeFiCh/oracle-adapters/blob/main/packages/salmon-fetch/src/FetchAsJson.ts) instead. It does the conversion of numbers to BigNumbers too.

2021-10-27 13:26 UTC, joeldavidw submitted a review, later dismissed

2021-11-01 06:22 UTC, monstrobishi submitted a review, later dismissed
This looks good, approving the PR

If you're able can you do a quick smoke test with a sample generated query from this adapter with a free finnhub API (quick signup) just to double check that it works live?

2021-11-01 06:57 UTC, monstrobishi approved these changes

2021-11-05 05:09 UTC, fuxingloh approved these changes

2021-11-05 05:10 UTC, merged